# Generated by Django 5.2.5 on 2025-08-22 12:33

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('team', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('date_created', models.DateTimeField(default=datetime.datetime(2025, 8, 22, 12, 33, 33, 178141, tzinfo=datetime.timezone.utc))),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='f1', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
