# Generated by Django 5.2.5 on 2025-08-22 12:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('f1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 22, 12, 37, 34, 106263, tzinfo=datetime.timezone.utc)),
        ),
    ]
