# Generated by Django 5.2.5 on 2025-08-28 08:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('f1', '0002_alter_driver_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='about',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='driver',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 28, 8, 0, 9, 197934, tzinfo=datetime.timezone.utc)),
        ),
    ]
