# Generated by Django 5.2.5 on 2025-08-28 10:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('f1', '0003_driver_about_alter_driver_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 28, 10, 4, 55, 693537, tzinfo=datetime.timezone.utc)),
        ),
    ]
