# Generated by Django 5.2.5 on 2025-08-29 09:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('f1', '0004_alter_driver_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='driver_image/'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 29, 9, 18, 34, 896217, tzinfo=datetime.timezone.utc)),
        ),
    ]
