# Generated by Django 5.2.5 on 2025-09-02 12:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('f1', '0005_driver_image_alter_driver_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
