# Generated by Django 5.2.5 on 2025-09-04 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('f1', '0007_like'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
